version: '3'
services:
    redis:
        image: redis:alpine
        container_name: redis-storage
        expose:
            - 6379
    app:
        build: .
        depends_on:
            - redis
        container_name: proxy-server
        ports:
            - 4444:4444
