version: '3'
services:
    redis:
        image: redis:alpine
        container_name: redis-storage
        expose:
            - "${REDIS_PORT}"

    app:
        build: .
        depends_on:
            - redis
        container_name: proxy-server
        env_file: .env
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
