version: '3'
services:
    test:
        container_name: test-client
        depends_on:
            - redis
            - app
        build:
            context: .
            dockerfile: Dockerfile.test
