version: '3'
services:
    test:
        container_name: cached-redis-proxy_test
        env_file: .env
        depends_on:
            - redis
            - app

        build:
            context: .
            dockerfile: Dockerfile.test
